### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by knkrth** [WSAyan/ysp#1]
Hi can you explain me how it works?

**Comment by WSAyan** [comment]
It's a service that sends latest sms from inbox to a particular number which you can modify by replacing "120398098213"(line: 46, class: startReciverService.java) with your number. If you want to spy on someone's message inbox you have to install this on victims phone. Unfortunately it does not work in KITKAT or higher versions for improved security reasons. :P

**Comment by knkrth** [comment]
Ok thanks :)
